{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "uptimehub-agent.fullname" . }}
  labels:
    {{- include "uptimehub-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "uptimehub-agent.fullname" . }}
  labels:
    {{- include "uptimehub-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "uptimehub-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "uptimehub-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
